Nop.Plugin.Uga.Partners/Models/PartnersModel.cs
using System;
using Nop.Web.Framework.Mvc;

namespace Nop.Plugin.Uga.Partners.Models
{
    [System.Diagnostics.DebuggerDisplay("{DebuggerDisplay,nq}")]
    public class PartnersModel : BaseNopEntityModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string City { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
		public string Latitude { get; set; }
		public string Longtitude { get; set; }
		public string Title { get; set; }
		public string Email { get; set; }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private string DebuggerDisplay
        {
            get { return ToString(); }
        }
    }
}

Nop.Plugin.Uga.Partners/Controllers/PartnersController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;
using Nop.Core;
using Nop.Core.Caching;
using Nop.Core.Domain.Catalog;
using Nop.Plugin.Uga.Partners.Infrastructure.Cache;
using Nop.Plugin.Uga.Partners.Models;
using Nop.Services.Catalog;
using Nop.Services.Customers;
using Nop.Services.Directory;
using Nop.Services.Localization;
using Nop.Services.Media;
using Nop.Services.Security;
using Nop.Services.Seo;
using Nop.Services.Stores;
using Nop.Services.Tax;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Security;
using Nop.Web.Framework.Kendoui;
using Nop.Web.Framework.Mvc;
using Nop.Core.Domain.Customers;
using Nop.Services.Common;
using Nop.Core.Data;
using Nop.Core.Domain.Common;
using System.Collections;
using Nop.Plugin.Uga.Partners.Services;
using Nop.Plugin.Uga.Partners.Domain;

namespace Nop.Plugin.Uga.Partners.Controllers
{
    [NopHttpsRequirement(SslRequirement.NoMatter)]
    public class PartnersController : BasePluginController
    {
        #region Fields

      
        private readonly IWorkContext _workContext;
        private readonly IPartnerService _pService;
        private readonly IRepository<PartnersRecord> _pRepository;
        

        #endregion

        #region Ctor

        public PartnersController(IPartnerService pService,
            IWorkContext workContext,
            IRepository<PartnersRecord> pRepository
           
            )
        {
            this._pService = pService;
            this._workContext = workContext;
            this._pRepository = pRepository;
        }

		#endregion

		#region Utilities

		#endregion

		#region Methods

		[ChildActionOnly]
		public ActionResult Configure() {
			return View("~/Plugins/Uga.Partners/Views/Partners/Configure.cshtml");
		}

		[HttpPost]
		public ActionResult Configure(DataSourceRequest command) {
		
			var partnerModels = new List<PartnersModel>();
			foreach (var partner in _pService.GetAll())
				partnerModels.Add(new PartnersModel()
                {
					 Address =partner.Address,
					 City=partner.City,
					 Description=partner.Description,
					 Email=partner.Email,
					 Latitude=partner.Latitude,
					 Longtitude=partner.Longtitude,
					 Name=partner.Name,
					 PostCode=partner.PostCode,
					 Telephone=partner.Telephone,
					 Title=partner.Title,
					 Id=partner.Id
				});

            DataSourceResult gridModel = new DataSourceResult()
            {
				Data = partnerModels,
				Total = partnerModels.Count
			};
			return Json(gridModel);
		}

		[HttpPost]
		[AdminAntiForgery]
		public ActionResult PartnersUpdate(PartnersModel model) {
	
			int partnerId = model.Id;
			PartnersRecord rec = new PartnersRecord();
			rec.Id = model.Id;
			rec.Latitude = model.Latitude;
			rec.Longtitude = model.Longtitude;
			rec.Name = model.Name;
			rec.PostCode = model.PostCode;
			rec.Telephone = model.Telephone;
			rec.Title = model.Title;
			rec.Address = model.Address;
			rec.City = model.City;
			rec.Description = model.Description;
			rec.Email = model.Email;

            if (rec.Id == 0)
            {
                _pService.InsertPartnerRecord(rec);
            }
            else
            {
                _pService.UpdatePartnerRecord(rec);
            }

            //_pService.SetSetting(string.Format("ShippingRateComputationMethod.FixedRate.Rate.ShippingMethodId{0}", shippingMethodId), rate);

            return new NullJsonResult();
		}


		[HttpPost]
		[AdminAntiForgery]
		public ActionResult PartnersCreate(PartnersModel model) {

			int partnerId = model.Id;
			PartnersRecord rec = new PartnersRecord();
			rec.Id = model.Id;
			rec.Latitude = model.Latitude;
			rec.Longtitude = model.Longtitude;
			rec.Name = model.Name;
			rec.PostCode = model.PostCode;
			rec.Telephone = model.Telephone;
			rec.Title = model.Title;
			rec.Address = model.Address;
			rec.City = model.City;
			rec.Description = model.Description;
			rec.Email = model.Email;

			if (rec.Id == 0)
				_pService.InsertPartnerRecord(rec);
			else
				_pService.UpdatePartnerRecord(rec);

			//_pService.SetSetting(string.Format("ShippingRateComputationMethod.FixedRate.Rate.ShippingMethodId{0}", shippingMethodId), rate);

			return new NullJsonResult();
		}

		[HttpPost]
		[AdminAntiForgery]
		public ActionResult PartnersDelete(PartnersModel model) {


			PartnersRecord rec = new PartnersRecord();
			rec.Id = model.Id;

			_pService.DeletePartner(rec);


			//_pService.SetSetting(string.Format("ShippingRateComputationMethod.FixedRate.Rate.ShippingMethodId{0}", shippingMethodId), rate);

			return new NullJsonResult();
		}



        public ActionResult Index()
        {
            return View("~/Plugins/Uga.Partners/Views/Partners/Index.cshtml");
        }


        [HttpPost]
        public ActionResult PartnersGridList(DataSourceRequest request, string id) {
            IList<PartnersModel> partners;
            if (!string.IsNullOrEmpty(id))
            {
                partners = (whereReduce(id)).Distinct().ToList();
            }
            else {
                 partners = (from c in _pRepository.Table.AsEnumerable()
                             select getPartnerDetails(c)).Distinct().ToList();
            }

            var gridModel = new DataSourceResult {
                Data = partners,
                Total = partners.Count()
            };

            return Json(gridModel, JsonRequestBehavior.AllowGet);
        }

        private IEnumerable<PartnersModel> whereReduce(string id)
        {
            return from c in _pRepository.Table.AsEnumerable()
                   where (c.City.ToUpper().Contains(id.ToUpper()) || c.PostCode.ToUpper().Contains(id.ToUpper()))
                   select getPartnerDetails(c);
        }

        public ActionResult PartnersList(string id)
        {
            IList<PartnersModel> partners;
            if (!string.IsNullOrEmpty(id))
            {
                partners = (whereReduce(id)).Distinct().ToList();

            }
            else {
                partners = (from c in _pRepository.Table.AsEnumerable()
                            select getPartnerDetails(c)).Distinct().ToList();
            }
           

            return Json(partners, JsonRequestBehavior.AllowGet);
        }

        private static PartnersModel getPartnerDetails(PartnersRecord c)
        {
            return new PartnersModel
            {
                Id = c.Id,
                Name = c.Name,
                Title = c.Description,
                Email = c.Email,
                Description = c.Description,
                Telephone = c.Telephone,
                PostCode = c.PostCode,
                Address = c.Address,
                City = c.City,
                Latitude = c.Latitude,
                Longtitude = c.Longtitude
            };
        }

        #endregion
    }
}   

Nop.Plugin.Uga.Partners/Views/Partners/Configure.cshtml
@{
    Layout = "";
}
@Html.AntiForgeryToken()
<table class="adminContent">
    <tr>
        <td>
            <div id="partners-grid"></div>

            <script>
                $(document).ready(function () {
                    $("#partners-grid").kendoGrid({
                        toolbar: ["create"],
                        dataSource: {
                            type: "json",
                            transport: {
                                read: {
                                    url: "@Html.Raw(Url.Action("Configure", "Partners", new RouteValueDictionary { { "Namespaces", "Nop.Plugin.Uga.Partners.Controllers" }, { "area", "" } }))",
                                    type: "POST",
                                    dataType: "json",
                                    data: addAntiForgeryToken
                                },
                                create: {
                                     url:"@Html.Raw(Url.Action("PartnersCreate", "Partners", new RouteValueDictionary { { "Namespaces", "Nop.Plugin.Uga.Partners.Controllers" }, { "area", "" } }))",
                                    type: "POST",
                                    dataType: "json",
                                    data: addAntiForgeryToken
                                },
                                update: {
                                    url:"@Html.Raw(Url.Action("PartnersUpdate", "Partners", new RouteValueDictionary { { "Namespaces", "Nop.Plugin.Uga.Partners.Controllers" }, { "area", "" } }))",
                                    type: "POST",
                                    dataType: "json",
                                    data: addAntiForgeryToken
                                },
                                    destroy: {
                                        url: "@Html.Raw(Url.Action("PartnersDelete", "Partners", new RouteValueDictionary { { "Namespaces", "Nop.Plugin.Uga.Partners.Controllers" }, { "area", "" } }))",
                                        type: "POST",
                                        dataType: "json",
                                        data: addAntiForgeryToken
                                    }
                            },
                            schema: {
                                data: "Data",
                                total: "Total",
                                errors: "Errors",
                                model: {
                                    id: "Id",
                                    fields: {
                                        Name: { editable: true, type: "string" },
                                        Description: { editable: true, type: "string" },
                                        City: { editable: true, type: "string" },
                                        Telephone: { editable: true, type: "string" },
                                        Address: { editable: true, type: "string" },
                                        PostCode: { editable: true, type: "string" },
                                        Latitude: { editable: true, type: "string" },
                                        Longtitude: { editable: true, type: "string" },
                                        Title: { editable: true, type: "string" },
                                        Email: { editable: true, type: "string" },

                                    }
                                }
                            },
                            requestEnd: function (e) {
                                if (e.type == "update") {
                                    this.read();
                                }
                            },
                            error: function (e) {
                                display_kendoui_grid_error(e);
                                // Cancel the changes
                                this.cancelChanges();
                            },
                            serverPaging: true,
                            serverFiltering: true,
                            serverSorting: true
                        },
                        pageable: {
                            refresh: true,
                            numeric: false,
                            previousNext: false,
                            info: false
                        },
                        editable: {
                            confirmation: false,
                            mode: "inline"
                        },
                        scrollable: false,
                        columns: [{
                            field: "Name",
                            title: "Name",
                            width: 200
                        }, {
                                field: "Description",
                            title: "Description",
                            width: 200,

                            },
                             {
                                 field: "City",
                                 title: "City",
                                width: 100,

                        },
                             {
                                 field: "Telephone",
                                 title: "Telephone",
                                 width: 100,

                             },
                             {
                                 field: "Address",
                                 title: "Address",
                                 width: 200,

                             },
                             {
                                 field: "PostCode",
                                 title: "PostCode",
                                 width: 70,

                             },
                             {
                                 field: "Latitude",
                                 title: "Latitude",
                                 width: 100,

                             },
                             {
                                 field: "Longtitude",
                                 title: "Longtitude",
                                 width: 100,

                             },
                             {
                                 field: "Title",
                                 title: "Title",
                                 width: 100,

                             },
                             {
                                 field: "Email",
                                 title: "Email",
                                 width: 100,

                             },
                        {
                            command: { name: "edit", text: "@T("Admin.Common.Edit")" },

                            title: "@T("Admin.Common.Edit")",
                            width: 150
                             },
                        {
                            command: { name: "delete", text: "@T("Admin.Common.Delete")" },

                            title: "@T("Admin.Common.Delete")",
                            width: 150
                        }
                        ]
                    });
                });
            </script>
        </td>
    </tr>
</table>

Nop.Plugin.Uga.Partners/Views/Partners/Index.cshtml
@model PartnersModel
@using System.Globalization;
@using Nop.Plugin.Uga.Partners.Models;

@{
    Layout = "~/Views/Shared/_ColumnsOne.cshtml";
}






<script type="text/javascript">
    var gmarkers = [];
    var map;




    $(document).ready(function () {

        $('#showGrid').click(function (e) {

            $("#customers-grid").data("kendoGrid").dataSource.read();
            $("#customers-grid").css("display", "block");

            var mapProp = {
                center: new google.maps.LatLng(40.67418, 22.80549), //Greece Lat Long
                zoom: 6,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            for (i = 0; i < gmarkers.length; i++) {
                gmarkers[i].setMap(null);
            }

            var purl = '@Url.Action("PartnersList", "Partners", new { id = "__param__" })';
            purl = purl.replace('__param__', $("#searchTerm").val());

            $.ajax({
                type: "GET",
                url: purl, //"../Map/Search"
                contentType: "application/json; charset=utf-8",
                data: additionalInfo,
                dataType: "json",
                success: function (data) {
                    var table = "<table class='table'>";
                    $.each(data, function (index, value) {
                        table += "<tr><td>" + value.Name + "</td></tr>";
                        var latlng = new google.maps.LatLng(value.Latitude, value.Longtitude);
                        var marker = new google.maps.Marker({
                            position: latlng,
                            map: map,
                          
                            title: value.Description + '\n' + value.Name + '\n ' + value.Address + ' PostalCode: ' + value.PostCode + '\n' + value.Telephone + '\n' + value.Email
                        });

                        gmarkers.push(marker);

                    });
                    table += "</table>";
                    $("#myData").html(table);


                }
            });
            map = new google.maps.Map(document.getElementById("googleMap"), mapProp);

        });

        onPageLoad();
    });

    function onPageLoad() {


        function initialize() {

            $("#customers-grid").data("kendoGrid").dataSource.read();
            $("#customers-grid").css("display", "block");

            var mapProp = {
                center: new google.maps.LatLng(40.67418, 22.80549), //Greece Lat Long
                zoom: 6,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };

            for (i = 0; i < gmarkers.length; i++) {
                gmarkers[i].setMap(null);
            }


            $.ajax({
                type: "POST",
                url: '@Url.Action("PartnersList", "Partners")', //"../Map/Search"
                contentType: "application/json; charset=utf-8",

                dataType: "json",
                success: function (data) {
                    var table = "<table class='table'>";
                    $.each(data, function (index, value) {
                        table += "<tr><td>" + value.Name + "</td></tr>";
                        var latlng = new google.maps.LatLng(value.Latitude, value.Longtitude);
                        var marker = new google.maps.Marker({
                            position: latlng,
                            map: map,
                           
                            title: value.Description + '\n' + value.Name + '\n ' + value.Address + ' PostalCode: ' + value.PostCode + '\n' + value.Telephone + '\n' + value.Email
                        });

                        gmarkers.push(marker);

                    });
                    table += "</table>";
                    $("#myData").html(table);


                }
            });
            map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
        }

        google.maps.event.addDomListener(window, 'load', initialize);

    }

</script>



<script>

   

    function additionalInfo() {
        var info = $("#searchTerm").val();
        if (info) {
            return {
                id: info
            };
        }
    }
</script>

<style>
    
    #googleMap {
        height: 550px;
        width: 100%;
    }
</style>


<div class="page home-page">
    <div class="page-body">
        <span id="lbSearch">@T("Uga.Partners.Search").Text</span> 
        <input type="text" id="searchTerm" name="text" value="" /><br />
        <input id='showGrid' type="button" value="@T("Search.Searchbox.Tooltip")" />

        <h2>@T("Uga.Partners.Shops")</h2>
        <br />
        <div class="row">
           
            <div class="col-md-6">
                <table class="adminContent">
                    <tr>
                        <td>
                            <div id="customers-grid"></div>

                            <script>
                    $(document).ready(function () {
                        $("#customers-grid").kendoGrid({
                            autoBind: false,
                            dataSource: {
                                //group: { field: "City" },
                                type: "json",
                                transport: {
                                    read: {
                                        url: "@Html.Raw(Url.Action("PartnersGridList", "Partners"))",
                                        type: "POST",
                                        dataType: "json",
                                        data: additionalInfo
                                    }
                                },
                                schema: {
                                    data: "Data",
                                    total: "Total",
                                    errors: "Errors"
                                },
                                error: function(e) {
                                    display_kendoui_grid_error(e);
                                    this.cancelChanges();
                                },
                                pageSize: 20,
                                serverPaging: true,
                                serverFiltering: true,
                                serverSorting: true
                            },
                            height: 550,
                            sortable: {
                                mode: "single",
                                allowUnsort: false
                            },
                            pageable: false,
                            scrollable: true,
                            selectable:true,
                            columns: [

                                {
                                    field: "Title",
                                    title: "@T("Admin.Customers.Customers.Fields.FullName")",
                                    width: 150
                                },


                               {
                                   field: "Telephone",
                                    title: "@T("Admin.Customers.Customers.Fields.Phone")",
                                    width: 90
                                },


                               {
                                   field: "City",
                                   title: "@T("Admin.Customers.Customers.Fields.City")",
                                width: 80
                               },

                                {
                                    field: "Address",
                                    title: "@T("Admin.Customers.Customers.Fields.StreetAddress")",
                                width: 100
                                },
                           {
                               field: "PostCode",
                                title: "@T("Admin.Customers.Customers.Fields.ZipPostalCode")",
                                width: 50
                           },
                           {
                               field: "Email",
                               title: "@T("Admin.Customers.Customers.Fields.Email")",
                                width: 100
                    },
                          ]
                        });
                    });
                            </script>

                            <script type="text/javascript">

                    var selectedIds = [];

                    $(document).ready(function () {

                        //search button
                        $('#search-customers').click(function () {
                            var grid = $('#customers-grid').data('kendoGrid');
                            grid.dataSource.page(1); //new search. Set page size to 1
                            //grid.dataSource.read(); we already loaded the grid above using "page" function
                            //clear selected checkboxes
                            $('.checkboxGroups').attr('checked', false).change();
                            selectedIds = [];
                            return false;
                        });


                        @*$("#@Html.FieldIdFor(model => model.SearchCompany)").keydown(function (event) {
                            if (event.keyCode == 13) {
                                $("#search-customers").click();
                                return false;
                            }
                        });*@


                    });





            function additionalData() {



                            @*var data = {
                                SearchCompany: $('#@Html.FieldIdFor(model => model.SearchCompany)').val(),
                                SearchZipPostalCode: $('#@Html.FieldIdFor(model => model.SearchZipPostalCode)').val()
                            };
                            addAntiForgeryToken(data);
                            return data;*@
                        }
                            </script>
                        </td>
                    </tr>
                </table>
            </div>
           
            <div class="col-md-6">

                <div id="googleMap"></div>
            </div>
        </div>
       
        @*<br />
        <div class="row">
            <div class="col-lg-12" id="partnersLogosWrapper">
                <h2>@T("Uga.Partners.Chains")</h2>
                <div class="partnersLogos">
                    <img src="~/Content/Images/praktiker.jpg" class="img-responsive" />
                    <img src="~/Content/Images/masoutis.jpg" class="img-responsive" />
                    <img src="~/Content/Images/xalkiadakis.jpg" class="img-responsive" />
                    <img src="~/Content/Images/proodos.jpg" class="img-responsive" />
                    <img src="~/Content/Images/ellhnika.jpg" class="img-responsive" />
                </div>
            </div>
        </div>*@
          
        </div>
</div>

Nop.Plugin.Uga.Partners/Views/Partners/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Partners</title>
    <link href="@Url.Content("~/Plugins/Uga.Partners/Content/styles.css")" type="text/css" rel="stylesheet" />
    <script src="@Url.Content("~/Plugins/Uga.Partners/Scripts/jquery-1.10.2.min.js")"></script>
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
</head>
<body>
    <div class="master-wrapper-page">
        <div class="master-wrapper-main">
            @RenderBody()
        </div>
    </div>
</body>
</html>